# Generated by Django 5.2.12 on 2026-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title',
            new_name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('FULLSTACK', 'Fullstack'), ('DEVOPS', 'Devops'), ('QA_ENGINEER', 'QA Engineer'), ('UX/UI_DESIGNER', 'UX/UI Designer'), ('PRODUCT_MANAGER', 'Product Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('DATA_SCIENTIST', 'Data Scientist'), ('TECHNICAL_LEAD', 'Technical Lead')], default='BACKEND', max_length=255),
        ),
    ]
