# Generated by Django 5.2.12 on 2026-04-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_job_title_user_roles_user_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job',
            new_name='job_title',
        ),
    ]
