# Generated by Django 5.2.12 on 2026-04-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_job_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('FULLSTACK', 'Fullstack'), ('DEVOPS', 'Devops'), ('QA_ENGINEER', 'QA Engineer'), ('UX/UI_DESIGNER', 'UX/UI Designer'), ('PRODUCT_MANAGER', 'Product Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('DATA_SCIENTIST', 'Data Scientist'), ('TECHNICAL_LEAD', 'Technical Lead')], max_length=255, null=True),
        ),
    ]
