# Generated by Django 5.2.12 on 2026-04-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title',
            new_name='job_titles',
        ),
    ]
