# Generated by Django 5.2.12 on 2026-04-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_job_title_user_job_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_titles',
            new_name='job_title',
        ),
    ]
