# Generated by Django 5.2.12 on 2026-04-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_project_id_project_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='asigner',
            new_name='assigner',
        ),
    ]
